apiVersion: v1
kind: Secret
metadata:
  name: mica-secrets
type: Opaque
data:
  MICA_DB_PASSWORD: {{ .Values.mica.db.password | b64enc }}
  MICA_OIDC_SECRET: {{ .Values.mica.oidc.clientSecret | b64enc }}
  MICA_SHARED_SECRET: {{ .Values.mica.sharedSecret | b64enc }}
