# schema for the effective config
# used to validate the view data
name: /examples/config/effective-config
kind: /mica/kind/v1
schema:
  unevaluatedProperties: false
  type: object
  properties:
    app1:
      properties:
        key1:
          type: string
        key2:
          type: boolean
      required: [key1, key2]
    app2:
      properties:
        key1:
          type: integer
        key2:
          type: boolean
      required: [key1, key2]
  required: [app1, app2]
