name: Publish Helm Chart
on:
  workflow_dispatch: { }
jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Setup
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Lint Helm Charts
        run: |
          helm lint charts/mica-standalone/

      - name: Log in to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Charts
        run: |
          helm package charts/mica-standalone/ --version ${GITHUB_REF_NAME}

      - name: Login to GitHub Container Registry
        run: |
          helm registry login --username ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Publish Helm Charts
        run: |
          helm push mica-standalone-${GITHUB_REF_NAME}.tgz oci://ghcr.io/${GITHUB_REPOSITORY}
