name: Publish Docker Images

on:
  workflow_dispatch: { }

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: mica-ui/package-lock.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MICA_DOCKER_USERNAME }}
          password: ${{ secrets.MICA_DOCKER_PASSWORD }}

      - name: Publish Docker images
        run: |
          mvn -B -P github-packages -DskipTests \
            -Ddocker.skip=false \
            -Ddocker.loadOrPush=push \
            package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
